
package sk.kopr.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AjsPort", targetNamespace = "http://localhost:8888/ajs?wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AjsPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns sk.kopr.server.PridajStudentResponse
     */
    @WebMethod(action = "http://localhost:8888/ajs?wsdl/pridatUcastnika")
    @WebResult(name = "PridajStudentResponse", targetNamespace = "urn:X-kopr", partName = "parameters")
    public PridajStudentResponse pridatUcastnika(
        @WebParam(name = "PridajStudentRequest", targetNamespace = "urn:X-kopr", partName = "parameters")
        PridajStudentRequest parameters);

}
