
package sk.kopr.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AjsService", targetNamespace = "http://localhost:8888/ajs?wsdl", wsdlLocation = "file:/C:/Users/Admin/eclipse-workspace/WSDLtoCode/wsdl.wsdl")
public class AjsService
    extends Service
{

    private final static URL AJSSERVICE_WSDL_LOCATION;
    private final static WebServiceException AJSSERVICE_EXCEPTION;
    private final static QName AJSSERVICE_QNAME = new QName("http://localhost:8888/ajs?wsdl", "AjsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Admin/eclipse-workspace/WSDLtoCode/wsdl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AJSSERVICE_WSDL_LOCATION = url;
        AJSSERVICE_EXCEPTION = e;
    }

    public AjsService() {
        super(__getWsdlLocation(), AJSSERVICE_QNAME);
    }

    public AjsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AJSSERVICE_QNAME, features);
    }

    public AjsService(URL wsdlLocation) {
        super(wsdlLocation, AJSSERVICE_QNAME);
    }

    public AjsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AJSSERVICE_QNAME, features);
    }

    public AjsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AjsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AjsPort
     */
    @WebEndpoint(name = "AjsPort")
    public AjsPort getAjsPort() {
        return super.getPort(new QName("http://localhost:8888/ajs?wsdl", "AjsPort"), AjsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AjsPort
     */
    @WebEndpoint(name = "AjsPort")
    public AjsPort getAjsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8888/ajs?wsdl", "AjsPort"), AjsPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AJSSERVICE_EXCEPTION!= null) {
            throw AJSSERVICE_EXCEPTION;
        }
        return AJSSERVICE_WSDL_LOCATION;
    }

}
